updated_concept_lesson_mapping = {
    'The relationship between multiplication and repeated addition.': 'Multiplication and Repeated Addition',
    'Interpret products by drawing pictures.': 'Multiplication and Groups',
    'Identifying division and its components.': 'Division: Quotient, Dividend and Divisor',
    'Dividing a number into groups.': 'Dividing a Number into Groups',
    'Use multiplication to solve word problems using arrays and a symbol for the unknown.': 'Word Problems Involving Multiplication Using Arrays',
    'Use multiplication to solve word problems involving measurement quantities using the number line.': 'Word Problems Involving Multiplication Using the Number Line',
    'Use multiplication to solve word problems involving groups.': 'Word Problems Involving Multiplication Using Groups',
    'Use division to solve word problems involving dividing objects equally into groups.': 'Word Problems Involving Division Using Groups',
    'Use division to solve word problems using arrays.': 'Word Problems Involving Division Using Arrays',
    'The multiplication table.': 'The Multiplication Table',
    'Find the unknown whole product in a multiplication equation using the multiplication table.': 'Finding the Product Using the Multiplication Table',
    'Find the unknown factor in a multiplication equation using the multiplication table.': 'Finding the Unknown Factor Using the Multiplication Table',
    'Solve division problems using multiplication and the multiplication table.': 'Division Using Multiplication Table',
    'Using the commutative property to find products.': 'The Commutative Property of Multiplication',
    'Using the associative property to find products.': 'The Associative Property of Multiplication',
    'Using the distributive property to find products.': 'The Distributive Property of Multiplication',
    'Find the unknown factor in division problems using the multiplication table.': 'Finding the Unknown Factor Using the Multiplication Table',
    'Associativity and multiplication problems.': 'Associativity and Multiplication Problems',
    'Multiplication table and the distributive property.': 'Multiplication Table and the Distributive Property',
    'Division and properties of operations.': 'Division Using Properties of Operations',
    'Solve multi-step word problem using rounding.': 'Solving Multi-Step Word Problems Using Rounding',
    'Solve multistep word problems.': 'Solving Multi-Step Word Problems Using Rounding',
    'Identify even and odd numbers.': 'Even and Odd Numbers',
    'Adding odd and even numbers.': 'Adding Odd and Even Numbers',
    'Multiplying by even numbers.': 'Multiplying by Even Numbers',
    'Patterns in the multiplication table and the number 5.': 'Patterns in the Multiplication Table for the Number 5',
    'Understand the place value chart.': 'Place Value Chart',
    'Rounding numbers to the nearest 10.': 'Rounding to the Nearest Ten',
    'Rounding numbers to the nearest 100.': 'Rounding to the Nearest Hundred',
    'Rounding numbers to the nearest 10 and 100.': 'Rounding to the Nearest Ten and Hundred',
    'Recognize estimation and estimate sums using rounding.': 'Estimating Sums Using Rounding',
    'Solve word problems involving estimation of sums.': 'Estimating Sums in Word Problems',
    'Check for reasonableness of answers using rounding.': 'Reasonableness of Answers Using Rounding',
    'Recognize estimation and estimate differences using rounding': 'Solving Word Problems Using Estimation and Rounding',
    'Addition properties.': 'Addition Rules',
    'Addition using place value chart.': 'Addition Using Place Value Chart',
    'Addition of multi digit whole numbers.': 'Addition of Multi-Digit Whole Numbers',
    'Rules of subtraction.': 'Subtraction Rules',
    'Subtraction of multi-digit whole numbers.': 'Subtraction of Multi-Digit Whole Numbers',
    'Solve word problems about adding multi-digit whole numbers.': 'Addition of Multi-Digit Whole Numbers',
    'Solve word problems about subtracting multi-digit whole numbers.': 'Subtraction of Multi-Digit Whole Numbers',
    'Extend the multiplication table to the number 10.': 'Adding the Number 10 to the Multiplication Table',
    'Multiples of 10.': 'Multiples of Ten',
    'Multiply numbers by multiples of 10.': 'Multiplying Numbers by Multiples of Ten',
    'Introducing fractions.': 'Introducing Fractions',
    'Introducing equivalent fractions using visual models.': 'Equivalent Fractions Using Visual Models',
    'Introducing equivalent fractions using the number line.': 'Equivalent Fractions Using Visual Models',
    'Understand that one whole is a fraction whose numerator and denominator are equal.': 'Expressing Whole Numbers as Fractions',
    'Express whole numbers as fractions having 1 in the denominator using visual models.': 'Expressing Whole Numbers as Fractions',
    'Express whole numbers as fractions having 1 in the denominator using the number line.': 'Expressing Whole Numbers as Fractions',
    'Compare simple fractions using area models.': 'Comparing Fractions',
    'Compare simple fractions using the number line.': 'Comparing Fractions',
    'Compare fractions having equal denominators.': 'Comparing Fractions',
    'Solve word problems involving adding minutes using the number line.': 'Solving Word Problems Involving Adding Minutes',
    'Solve word problems involving subtracting minutes using the number line.': 'Solving Word Problems Involving Subtracting Minutes',
    'Measure mass using units of kilogram.': 'Measuring Mass',
    'Measure mass using units of gram.': 'Measuring Mass',
    'Subtract whole measurements of mass in standard units.': 'Operations with Mass Measurements',
    'Multiply whole measurements of mass using repeated addition.': 'Operations with Mass Measurements',
    'Multiplying whole measurements of volume using repeated addition.': 'Multiplying Measurements of Volume',
    'Multiply whole-number measurements of length of the sides of a rectangle to find the area in the context of a real-world problem.': 'Area of Rectangles',
    'Recognize squares as a sub-category of rectangles.': 'Properties of Squares and Rectangles',
    'Word Problems Involving Multiplication Using Arrays': 'Word Problems Involving Multiplication Using Arrays',
    'Word Problems Involving Multiplication Using the Number Line': 'Word Problems Involving Multiplication Using the Number Line',
    'Word Problems Involving Multiplication Using Groups': 'Word Problems Involving Multiplication Using Groups',
    'Word Problems Involving Division Using Groups': 'Word Problems Involving Division Using Groups',
    'Word Problems Involving Division Using Arrays': 'Word Problems Involving Division Using Arrays',
    'Finding the Unknown Factor in Division Problems': 'Finding the Unknown Factor Using the Multiplication Table',
    'Time in a Watch': 'Time in a Watch',
    'Time Estimates': 'Time Estimates',
    'Difference in Minutes Between Two Times within the Same Hour': 'Difference in Minutes Between Two Times within the Same Hour',
    'Multiplication and Groups': 'Multiplication and Groups',
    'Multiplication Using Arrays': 'Multiplication Using Arrays',
    'Division: Quotient, Dividend and Divisor': 'Division: Quotient, Dividend and Divisor',
    'Dividing a Number into Groups': 'Dividing a Number into Groups',
    'Division Using Arrays': 'Division Using Arrays',
    'Division Using Multiplication Table': 'Division Using Multiplication Table',
    'Division Using Properties of Operations': 'Division Using Properties of Operations',
    'The Multiplication Table': 'The Multiplication Table',
    'Patterns in the Multiplication Table for the Number 5': 'Patterns in the Multiplication Table for the Number 5',
    'Adding the Number 10 to the Multiplication Table': 'Adding the Number 10 to the Multiplication Table',
    'Finding the Product Using the Multiplication Table': 'Finding the Product Using the Multiplication Table',
    'Associativity and Multiplication Problems': 'Associativity and Multiplication Problems',
    'Multiplication Table and the Distributive Property': 'Multiplication Table and the Distributive Property',
    'Finding the Unknown Factor Using the Multiplication Table': 'Finding the Unknown Factor Using the Multiplication Table'
}

print("Updated concept-lesson mapping created successfully.")